Endpoint Management
cryptic-game/java-backend pull request #307
Opened 2021-05-26 22:12 UTC by Frederik-FJ

**Description**
Adds endpoints to the admin-panel to manage server endpoints

**Issue**
Closes #296 

**Testing Instructions**
Use the swagger-ui to test the endpoints

**Additional Notes**
Just used the existing functionality in the server module

2021-05-27 05:38 UTC, MarcelCoding requested changes

2021-05-27 05:38 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/SecurityConfiguration.java
> +                .pathMatchers("/server_management/**").hasRole("SERVER_MANAGEMENT")
Only the roles "website", "server_admin" and "moderator" are existing.

2021-05-27 05:38 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/dto/server_management/Endpoint.java
> +                    @JsonProperty("parameters") final List<Parameter> parameters) {
I think that parameters are not interesting for the admin panel.

2021-05-27 05:38 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +    private HttpClient httpClient;
Have a loop to the web client from spring. It provides mutch more functionality and could reduce the code.

2021-05-27 05:38 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/EndpointServiceImpl.java
> +                new JSONObject(Map.of("id", path)))
Use the object mapper to convert a object to a json string. But if you use the spring we client, you could pass in a object directly.

2021-05-27 05:38 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +    private HttpClient httpClient;
Ps: it is an addition to the reactor Http client.

2021-05-28 05:43 UTC, MarcelCoding requested changes

2021-05-28 05:43 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +                    .defaultHeader("authorization", this.config.getApiToken())
Use Http Headers constants from spring.

2021-05-28 05:43 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +                    throw new InternalServerErrorException("Got status code " + response.rawStatusCode() + " from the server");
There is a method to convert the response into an exception

2021-05-28 14:13 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +                            );
```suggestion
                    if (response.rawStatusCode() == 404) {
                        throw new NotFoundException(data.toJSONString(), "Element not found");
                    }
                    return response.createException();
```

2021-05-28 14:13 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/ServerCommunicationImpl.java
> +                            );
I've thought about something like that.

2021-05-28 16:48 UTC, JannikEmmerich requested changes

2021-05-28 16:48 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +}
Please use Spring Boot custom properties. 
https://www.baeldung.com/configuration-properties-in-spring-boot#1-spring-boot-22

2021-05-28 16:48 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/controller/server_management/EndpointController.java
> +import com.nimbusds.jose.shaded.json.JSONObject;
Don't use this `JSONObject`. Return a DTO, an ObjectNode or a Map instead.

2021-05-28 16:48 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/exception/InternalServerErrorException.java
> +}
You don't need this, because Spring Web Flux returns 500 if there is any exception thrown in the execution.

2021-05-28 16:48 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/model/server_management/DisabledEndpointModel.java
> +    @Column(name = "endpoint_path", unique = true, nullable = false)
```suggestion
    @Column(name = "endpoint_path", unique = true, nullable = false, updatable = false)
```

2021-05-28 16:48 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/service/server_management/EndpointService.java
> +import com.nimbusds.jose.shaded.json.JSONObject;
Same as I mentioned before.

2021-05-28 23:35 UTC, MarcelCoding requested changes
Some small last changes.

2021-05-28 23:35 UTC, MarcelCoding commented on admin-panel/src/main/resources/application.properties
> +gameserver.serverUrl = ${SERVER_URL:}
```suggestion
cryptic.admin-panel.api-token=${API_TOKEN:}
cryptic.admin-panel.server-url=${SERVER_URL:}
```

Properties files without spaces.

2021-05-28 23:35 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +@Setter
```suggestion
@Data
```
Here the use of @Data is better.

2021-05-28 23:35 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +@ConfigurationProperties(prefix = "gameserver")
```suggestion
@ConfigurationProperties(prefix = "cryptic.admin-panel")
```

2021-05-31 08:29 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +@Setter
We don't need the setters, do we?

2021-05-31 08:42 UTC, JannikEmmerich approved these changes

2021-05-31 10:50 UTC, MarcelCoding commented on admin-panel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}
I think this is generated at compile time. -> No need to push it.

2021-05-31 10:50 UTC, MarcelCoding commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +@Getter
```suggestion
import lombok.Setter;
import lombok.Data;
import lombok.AccessLevel;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@Setter(AccessLevel.NONE)
```

2021-05-31 10:51 UTC, MarcelCoding commented on admin-panel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}
https://github.com/cryptic-game/java-backend/blob/master/admin-panel/build.gradle#L24 This Annotation processor does it.

2021-05-31 12:08 UTC, JannikEmmerich commented on admin-panel/src/main/java/net/cryptic_game/backend/admin/Config.java
> +@Getter
This is useless!

2021-05-31 12:10 UTC, MarcelCoding approved these changes

2021-05-31 12:13 UTC, merged